version: '3.8'

services:
  moderator:
    build:
      context: . 
      dockerfile: Dockerfile  
    container_name: moderator_bot
    env_file: 
      - .env-
    volumes:
      - .:/app
      - ./bad_words.txt:/app/bad_words.txt
    command: /bin/sh -c "alembic --config /moderator/bot/alembic.ini upgrade head && python bot/main.py"
