version: '3.8'

services:
  moderator:
    build:
      context: . 
      dockerfile: Dockerfile  
    container_name: moderator_bot
    env_file: 
      - .env
    volumes:
      - .:/app
      - ./bad_words.txt:/app/bad_words.txt
    command: python bot/main.py